### ISSUE TITLE
I installed modules from windows like this

### ISSUE THREAD

**Issue by 1C0D** [conjuur/ImageVoodoo#2]
import bpy
from subprocess import check_call

try:
    from PIL import Image #done
except ImportError:
    pybin = bpy.app.binary_path_python
    check_call([pybin, '-m', 'pip', 'install', 'Pillow']) #win 
    from PIL import Image

try:
    import numpy as np #done
except ImportError:
    pybin = bpy.app.binary_path_python
    check_call([pybin, '-m', 'pip', 'install', 'numpy']) #win 
    import numpy as np
                        
try:
    import cv2 as cv #pb
except ImportError:
    pybin = bpy.app.binary_path_python
    check_call([pybin,'-m', 'pip', 'install', 'opencv-python']) #win
    import cv2 as cv

import os
from os import listdir
#import cv2 as cv
#import numpy as np
import random as rng
import math
#from PIL import Image
#import csv
from bpy_extras.io_utils import ImportHelper
from bpy_extras.object_utils import AddObjectHelper, object_data_add
from bpy.types import (Panel, Operator, PropertyGroup)
from bpy.props import (StringProperty,
                       FloatProperty,
                       PointerProperty,
                       BoolProperty,
                       IntProperty,
                       EnumProperty,
                       FloatVectorProperty
                       )

**Comment by conjuur** [comment]
Thank you.  I appreciate the help a lot!
